"""create duels and duel_members

Revision ID: 4ceb0547c9e0
Revises: 55a9c53aa00a
Create Date: 2025-12-27 13:47:35.730962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceb0547c9e0'
down_revision: Union[str, None] = '55a9c53aa00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duels_chat_id'), 'duels', ['chat_id'], unique=False)
    op.create_index(op.f('ix_duels_created_by'), 'duels', ['created_by'], unique=False)
    op.create_table('duel_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duel_id'], ['duels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duel_id', 'user_id', name='uq_duel_member')
    )
    op.create_index(op.f('ix_duel_members_duel_id'), 'duel_members', ['duel_id'], unique=False)
    op.create_index(op.f('ix_duel_members_user_id'), 'duel_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duel_members_user_id'), table_name='duel_members')
    op.drop_index(op.f('ix_duel_members_duel_id'), table_name='duel_members')
    op.drop_table('duel_members')
    op.drop_index(op.f('ix_duels_created_by'), table_name='duels')
    op.drop_index(op.f('ix_duels_chat_id'), table_name='duels')
    op.drop_table('duels')
    # ### end Alembic commands ###
