"""create step_entries

Revision ID: 55a9c53aa00a
Revises: c13ac92a81e2
Create Date: 2025-12-27 13:15:41.114451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a9c53aa00a'
down_revision: Union[str, None] = 'c13ac92a81e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_entries_chat_id'), 'step_entries', ['chat_id'], unique=False)
    op.create_index(op.f('ix_step_entries_day'), 'step_entries', ['day'], unique=False)
    op.create_index(op.f('ix_step_entries_user_id'), 'step_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_entries_user_id'), table_name='step_entries')
    op.drop_index(op.f('ix_step_entries_day'), table_name='step_entries')
    op.drop_index(op.f('ix_step_entries_chat_id'), table_name='step_entries')
    op.drop_table('step_entries')
    # ### end Alembic commands ###
