"""create sleep_sessions

Revision ID: a4e60d1a0f7e
Revises: 
Create Date: 2025-12-27 11:53:00.746655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e60d1a0f7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('gn_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gm_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_sessions_chat_id'), 'sleep_sessions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_sleep_sessions_user_id'), 'sleep_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_sessions_user_id'), table_name='sleep_sessions')
    op.drop_index(op.f('ix_sleep_sessions_chat_id'), table_name='sleep_sessions')
    op.drop_table('sleep_sessions')
    # ### end Alembic commands ###
