"""add reminded_at to sleep_sessions

Revision ID: c13ac92a81e2
Revises: a4e60d1a0f7e
Create Date: 2025-12-27 12:29:13.331854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13ac92a81e2'
down_revision: Union[str, None] = 'a4e60d1a0f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep_sessions', sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleep_sessions', 'reminded_at')
    # ### end Alembic commands ###
